### ISSUE TITLE
Remove deleted files / directories

### ISSUE THREAD

**Issue by HaleTom** [camdencheek/fre#18]
How can I easily remove deleted files / directories from the output?

Ideally I could run a command to remove all of these, or only entries that match a glob or regex.

**Comment by HaleTom** [comment]
Ah, I just saw the following in README:

```
# Purge directories that no longer exist
fre --sorted | while read dir ; do if [ ! -d "$dir" ] ; then fre --delete "$dir";  fi ; done
```

Just change to `! -e` for existence check, and use a better variable name like `$entry`.

**Comment by camdencheek** [comment]
Glad the readme example helped!
