### ISSUE TITLE
fre --stat: allow to customize the number of digits shown

### ISSUE THREAD

**Issue by xsteve** [camdencheek/fre#22]
I use fre to sort my file bookmarks. It is a really useful tool for me.
When I have not visited some files for a longer time period the shown score is 0.000
It would be nice to allow showing more than 3 digits. That way 0.000 would be e.g. shown as 0.00004
This could be done by e.g adding the option --stat-digits 5 (defaulting to the current value 3)

**Comment by xsteve** [comment]
Thanks for getting back to me.
I am fine with both.
Adding an option would be better for backwards compatibility. But that is not important for me...

**Comment by camdencheek** [comment]
Just published v0.4.0, which notably includes the `--stat-digits` option. Thanks for reaching out!
